language: ruby

sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - ruby-head
  - rbx
  - jruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby
  fast_finish: true
